ACQUISITION:
  EMMISION_IMAGE_TIME_MINUTES: 10

ACTIVITY:
  HOT: 0.79
  BACKGROUND: 0.079
  RATIO: 9.91

PHANTHOM:
  ROI_DEFINITIONS_MM:
    - center_yx: [211, 171]
      diameter_mm: 37
      color: "red"
      alpha: 0.18
      name: "hot_sphere_37mm"
    - center_yx: [187, 184]
      diameter_mm: 28
      color: "orange"
      alpha: 0.18
      name: "hot_sphere_28mm"
    - center_yx: [187, 212]
      diameter_mm: 22
      color: "gold"
      alpha: 0.18
      name: "hot_sphere_22mm"
    - center_yx: [211, 226]
      diameter_mm: 17
      color: "lime"
      alpha: 0.18
      name: "hot_sphere_17mm"
    - center_yx: [235, 212]
      diameter_mm: 13
      color: "cyan"
      alpha: 0.18
      name: "hot_sphere_13mm"
    - center_yx: [235, 184]
      diameter_mm: 10
      color: "blue"
      alpha: 0.18
      name: "hot_sphere_10mm"

ROIS:
  CENTRAL_SLICE: 172

FILE:
  USER_PATTERN: "frame(\\d+)"
  CASE: "Test"
